all done
mate-academy/jv-oop pull request #1043
Opened 2022-10-26 17:02 UTC by diana-lomei

2022-10-26 18:27 UTC, kateryna-deshchinska requested changes
Java Cl checks failed. Before making a Pull Request (or a new commit to an already existing PR), you need to write the mvn clean package command in the terminal and make sure that all checks pass. After that, the mentor will be able to review the homework

2022-10-26 18:27 UTC, kateryna-deshchinska commented on src/main/java/core/basesyntax/Machine.java
> +}
```suggestion
}

```

2022-10-27 10:09 UTC, Rommelua requested changes
![image](https://user-images.githubusercontent.com/20326858/198257104-b57062eb-fafa-4e2b-800b-feeea8943bfa.png)
Java Cl checks failed. Before making a Pull Request (or a new commit to an already existing PR), you need to write the mvn clean package command in the terminal and make sure that all checks pass. After that, the mentor will be able to review the homework

2022-10-29 09:19 UTC, aaananas approved these changes

2025-02-21 11:55 UTC, closed without merging