task done
mate-academy/jv-oop pull request #1044
Opened 2022-10-26 17:32 UTC by Kateryna-Takhtai

top basic task is done.

2022-10-26 18:42 UTC, kateryna-deshchinska requested changes

2022-10-26 18:42 UTC, kateryna-deshchinska commented on src/main/java/core/basesyntax/MainApp.java
> +        Machine[] machines = new Machine[]{truck,bulldozer,excavator};
```suggestion
        Machine[] machines = new Machine[]{truck, bulldozer, excavator};
```

2022-10-26 18:42 UTC, kateryna-deshchinska commented on src/main/java/core/basesyntax/Bulldozer.java
> +        System.out.println("Bulldozer does work");
```suggestion
        System.out.println("Bulldozer start working);
```

2022-10-26 18:42 UTC, kateryna-deshchinska commented on src/main/java/core/basesyntax/Bulldozer.java
> +        System.out.println("Bulldozer does not work");
```suggestion
        System.out.println("Bulldozer finished working");
```

2022-10-26 18:42 UTC, kateryna-deshchinska commented on src/main/java/core/basesyntax/Bulldozer.java
> +        System.out.println("Bulldozer does not work");
Make message for different machine more similar, you may use my example below

2022-10-26 18:42 UTC, kateryna-deshchinska commented on src/main/java/core/basesyntax/MainApp.java
> +
```suggestion
```

2022-10-26 18:42 UTC, kateryna-deshchinska commented on src/main/java/core/basesyntax/MainApp.java
```suggestion
```

2022-10-27 10:04 UTC, Rommelua approved these changes
I approve, but do not add redundant empty lines and fix **all** mentor's comments before asking new review.

2022-10-27 10:04 UTC, Rommelua commented on src/main/java/core/basesyntax/MainApp.java
> +
not fixed...

2023-08-05 13:17 UTC, closed without merging