jv-oop
mate-academy/jv-oop pull request #1652
Opened 2023-09-13 04:13 UTC by almanac4444

Please check the task

2023-09-13 10:18 UTC, Rommelua requested changes
Java Cl checks failed. Before making a Pull Request (or a new commit to an already existing PR), you need to write the mvn clean package command in the terminal and make sure that all checks pass. After that, the mentor will be able to review the homework

![image](https://github.com/mate-academy/jv-oop/assets/20326858/7f4bd45c-65c2-43ec-ba2e-8d7df7decfcd)

2023-09-14 10:42 UTC, Rommelua requested changes
https://mate-academy.github.io/jv-program-common-mistakes/java-core/oop/oop

Before you create PR with your homework, you need to go through the checklist under the task and correct all the points described there.

2023-09-14 10:42 UTC, Rommelua commented on src/main/java/core/basesyntax/Bulldozer.java
> +    public void doWork() {
![image](https://github.com/mate-academy/jv-oop/assets/20326858/93f53876-12e8-4dcc-809c-8f160ea7f168)

2023-09-15 11:56 UTC, sokimaaa approved these changes

2026-02-10 08:03 UTC, closed without merging