ф
mate-academy/jv-oop pull request #1702
Opened 2023-10-06 15:57 UTC by DankevichMisha

2023-10-06 15:58 UTC, DankevichMisha commented
ок

2023-10-09 06:53 UTC, bhdnchui requested changes

2023-10-09 06:53 UTC, bhdnchui commented on jv-oop12/README.md
> +# jv-oop
Redundant file.

2023-10-09 06:53 UTC, bhdnchui commented on jv-oop12/checklist.md
> +## Common mistakes (jv-oop)
Redundant file.

2023-10-09 06:53 UTC, bhdnchui commented on jv-oop12/src/main/java/core/basesyntax/Bulldozer.java
> +    @java.lang.Override
```suggestion
    @Override
```

2023-10-09 06:53 UTC, bhdnchui commented on jv-oop12/src/main/java/core/basesyntax/MainApp.java
> +        Machine[] machines = new Machine[3];
Make constant.

2023-10-09 06:53 UTC, bhdnchui commented on jv-oop12/src/main/java/core/basesyntax/String.java
> +}
```suggestion

```

2023-10-09 06:53 UTC, bhdnchui commented on jv-oop12/src/test/java/core/basesyntax/MainAppTest.java
> +}
```suggestion

```

2023-10-09 10:27 UTC, DankevichMisha commented on jv-oop12/README.md
> +# jv-oop
okay

2023-10-09 10:28 UTC, DankevichMisha commented on jv-oop12/checklist.md
> +## Common mistakes (jv-oop)
ok

2023-10-09 10:36 UTC, DankevichMisha commented on jv-oop12/src/main/java/core/basesyntax/MainApp.java
> +        Machine[] machines = new Machine[3];
like a :
final Machine[] machines = new Machine[3]; ?

2023-10-09 10:36 UTC, DankevichMisha commented on jv-oop12/src/main/java/core/basesyntax/String.java
> +}
delete this?

2023-10-13 08:16 UTC, DankevichMisha commented
+

2023-10-13 08:17 UTC, DankevichMisha commented
correct mistakes

2023-10-13 10:22 UTC, Rommelua requested changes
Delete this folder jv-oop12 - we do not need it
![image](https://github.com/mate-academy/jv-oop/assets/20326858/0f014e11-00ac-4e7a-9529-950921de229b)

2023-10-13 20:00 UTC, DankevichMisha reviewed
//

2023-10-13 20:25 UTC, DankevichMisha reviewed
вроде бы оно

2023-11-02 15:41 UTC, Rommelua requested changes
Треба видалити зайві папки

2023-11-02 17:54 UTC, closed without merging