Finished my work
mate-academy/jv-oop pull request #1792
Opened 2023-12-08 15:52 UTC by Rostyk12

2023-12-08 16:01 UTC, kerrrusha requested changes
your CI Checks at the PR page are failed, please fix them
(There are 22 errors reported by Checkstyle 9.3)
![image](https://github.com/mate-academy/jv-oop/assets/73041091/f992c8a0-3646-4ef4-924c-e6d888c6a658)

2023-12-08 17:30 UTC, kerrrusha requested changes

2023-12-08 17:30 UTC, kerrrusha commented on src/main/java/core/basesyntax/Excavator.java
> +
redundant blank line
```suggestion
```

2023-12-08 17:30 UTC, kerrrusha commented on src/main/java/core/basesyntax/MainApp.java
> +        }
better not to name variables (excluding counters etc) with single letter
```suggestion
        for (Machine machine : machines) {
            machine.doWork();
            machine.stopWork();
        }
```

2023-12-08 17:30 UTC, kerrrusha commented on src/main/java/core/basesyntax/Truck.java
> +
redundant blank line
```suggestion
```

2023-12-09 14:51 UTC, sokimaaa approved these changes

2025-02-17 19:43 UTC, closed without merging