machine classes are created and methods are implemented
mate-academy/jv-oop pull request #1825
Opened 2023-12-31 10:05 UTC by vladshender

2023-12-31 12:05 UTC, olekskov reviewed
Good job overall but require style imporvements

2023-12-31 12:05 UTC, olekskov commented on src/main/java/core/basesyntax/MainApp.java
> +        Machine[] cars = {truck, bulldozer, excavator};
Variables should be introduced when they are reused in different places 
or when we give understandable name for complicated code part and thus increasing readability.
This is not the case, used only once, not more clear than command under variable
```suggestion
        Machine[] cars = {new Truck(), new Bulldozer(), new Excavator()};
```

2023-12-31 12:05 UTC, olekskov commented on src/main/java/core/basesyntax/MainApp.java
> +        }
we may simplify some names but not in a way it changes the meaning of variable content. Excavator and bulldozer are not cars :)
```suggestion
        for (Machine machine : machines) {
            machines.doWork();
            machines.stopWork();
        }
```

2023-12-31 12:06 UTC, olekskov requested changes
Please check comments above

2024-01-04 14:22 UTC, okuzan approved these changes
Good job, make sure you are prepared to use Java 17 on your next projects

2024-01-04 14:23 UTC, okuzan requested changes
Build failed, please fix the build!

2024-01-04 15:41 UTC, olekskov approved these changes

2026-03-08 07:36 UTC, closed without merging