Top m
mate-academy/jv-oop pull request #2031
Opened 2024-06-05 13:35 UTC by Hot00Tea

2024-06-05 13:45 UTC, MentorMateAcademy requested changes
Your task not finished

2024-06-05 13:49 UTC, Hot00Tea commented
![Screenshot_1](https://github.com/mate-academy/jv-oop/assets/46758793/60143eb5-09ce-4918-aa43-2942da22c634)
 
В мене помилка яку я не знаю як виправити

2024-06-10 09:56 UTC, Hot00Tea commented
Я здав чи треба переробити щось?

2024-09-18 10:48 UTC, Hot00Tea commented
Done

2024-09-18 17:39 UTC, okuzan requested changes

2024-09-18 17:39 UTC, okuzan commented on src/main/java/core/basesyntax/Truck.java
> +
add implementation

2024-09-18 17:39 UTC, okuzan commented on src/main/java/core/basesyntax/Truck.java
> +
don't leave an emtpy line after method/class definition

2024-09-18 17:39 UTC, okuzan commented on src/main/java/core/basesyntax/MainApp.java
> +    private Machine[] machines = {excavator, truck, bulldozer};
```suggestion
    private Machine[] machines = {new Excavator(), new Truck(), new Bulldozer()};
```

2024-09-18 17:58 UTC, Hot00Tea commented on src/main/java/core/basesyntax/Truck.java
> +
Не розумію як

2024-09-19 07:59 UTC, liliia-ponomarenko requested changes
Let's add realization to your solution ;)

2024-09-19 07:59 UTC, liliia-ponomarenko commented on src/main/java/core/basesyntax/Bulldozer.java
> +
Let's add the realization to all override methods in classes that extend Machine 
for example: 
```suggestion
 System.out.println("Bulldozer started working!");
```

2024-09-19 07:59 UTC, liliia-ponomarenko commented on src/main/java/core/basesyntax/Bulldozer.java
> +
add realization

2024-09-19 07:59 UTC, liliia-ponomarenko commented on src/main/java/core/basesyntax/Excavator.java
> +
redundant empty line 
```suggestion
```

2024-09-19 07:59 UTC, liliia-ponomarenko commented on src/main/java/core/basesyntax/Machine.java
> +
redundant empty line 
```suggestion
```

2024-09-19 07:59 UTC, liliia-ponomarenko commented on src/main/java/core/basesyntax/MainApp.java
> +
redundant empty line

2024-09-19 07:59 UTC, liliia-ponomarenko commented on src/main/java/core/basesyntax/Excavator.java
> +}
add realization

2024-09-19 07:59 UTC, liliia-ponomarenko commented on src/main/java/core/basesyntax/Truck.java
> +    }
add realization

2024-09-19 07:59 UTC, liliia-ponomarenko commented on src/main/java/core/basesyntax/Truck.java
> +
redundant empty line

2024-09-19 11:31 UTC, Elena-Bruyako requested changes

2024-09-19 11:31 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/Bulldozer.java
> +
[Please don't add redundant empty lines to your code.](https://github.com/mate-academy/jv-oop/blob/master/checklist.md#please-dont-add-redundant-empty-lines-to-your-code)

2024-09-19 11:31 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/Excavator.java
> +
same comment

2024-09-19 11:31 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/Machine.java
> +
same comment

2024-09-19 11:31 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/MainApp.java
> +    public void main() {
```suggestion
    public static void main(String[] args) {
```

2024-09-19 11:31 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/MainApp.java
> +    private Machine[] machines = {new Excavator(), new Truck(), new Bulldozer()};
replace to main method

2024-09-19 11:31 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/Truck.java
> +
[Please don't add redundant empty lines to your code.](https://github.com/mate-academy/jv-oop/blob/master/checklist.md#please-dont-add-redundant-empty-lines-to-your-code)

2024-09-19 12:50 UTC, Elena-Bruyako requested changes

2024-09-19 12:50 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/Bulldozer.java
> +
Do you have some questions about this comment? [Please don't add redundant empty lines to your code.](https://github.com/mate-academy/jv-oop/blob/master/checklist.md#please-dont-add-redundant-empty-lines-to-your-code)

2024-09-19 12:50 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/Bulldozer.java
> +
remove 4 line

2024-09-19 12:50 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/Bulldozer.java
> +
remove 8 line

2024-09-19 12:50 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/Excavator.java
> +
remove 4 line

2024-09-19 12:50 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/Truck.java
> +
remove 4 line

2024-09-20 11:09 UTC, Elena-Bruyako approved these changes

2024-12-23 13:33 UTC, closed without merging