Adding classes machin etc
mate-academy/jv-oop pull request #2066
Opened 2024-07-04 10:58 UTC by ynazarets

2024-07-04 10:58 UTC, mateacademy-ai-mentor approved these changes
The messages in the methods could be more informative.

2024-07-04 10:58 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/Bulldozer.java
> +        System.out.println("Bulldozer is now working.");
The message in the 'doWork' method should be more informative and indicate that it is a Bulldozer that is working.

2024-07-04 10:58 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/Bulldozer.java
> +        System.out.println("Bulldozer has stopped working.");
Similarly, the message in the 'stopWork' method should be more informative and indicate that it is a Bulldozer that has stopped working.

2024-07-04 10:58 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/Excavator.java
> +        System.out.println("Excavator is now working.");
The message 'Excavator is now working.' could be more informative by specifying the type of machine, for example, 'Excavator machine is now working.' to provide clarity.

2024-07-04 10:58 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/Excavator.java
> +        System.out.println("Excavator has stopped working.");
Similarly, the message 'Excavator has stopped working.' can be improved for clarity by specifying the type of machine, such as 'Excavator machine has stopped working.'

2024-07-04 10:58 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/MainApp.java
> +        System.out.println("Machines working all day and then...\n");
The message printed to the console is not informative about the type of machines that are working. Consider improving the message to reflect the types of machines that have been working, such as 'Excavator, Bulldozer, and Truck have finished their work for the day'.

2024-07-04 10:58 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/Truck.java
> +        System.out.println("Truck is now working.");
The message printed should be more informative and indicate that it is a 'Truck' that is working. For example: 'Truck started its work.'

2024-07-04 10:58 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/Truck.java
> +        System.out.println("Truck has stopped working.");
Similarly, the stopWork message should clearly indicate that it is a 'Truck' that has stopped working. For instance: 'Truck has finished its work.'

2024-07-05 11:22 UTC, Elena-Bruyako requested changes

2024-07-05 11:22 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/MainApp.java
> +        Machine[] buildingMachines = new Machine[] {fv122, opc47, skania};
```suggestion
        Machine[] machines = {new Excavator(), new Bulldozer(), new Truck()};
```

2024-07-05 11:22 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/MainApp.java
> +            buildingMachines[i].doWork();
```suggestion
            buildingMachines[i].doWork();
            buildingMachines[i].stopWork();
```

2024-07-06 08:12 UTC, MentorMateAcademy approved these changes

2024-07-06 18:21 UTC, closed without merging