Hw oop
mate-academy/jv-oop pull request #2085
Opened 2024-07-26 17:19 UTC by layzimayner

2024-07-26 17:19 UTC, mateacademy-ai-mentor approved these changes
Great job on defining the `Machine` class as an abstract class with the required abstract methods! 👍 It seems like there are no critical issues affecting the functionality, so your Pull Request has been approved. Remember to consider the provided feedback for future improvements, such as making log messages more descriptive and adhering to code style guidelines. Keep up the good work! 😊

2024-07-26 17:19 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/Bulldozer.java
> +        System.out.println("Bulldozer start working");
The message in the 'doWork' method should indicate the type of Machine more informatively. Consider specifying that a Bulldozer is working, for example: 'Bulldozer is starting its work.'

2024-07-26 17:19 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/Bulldozer.java
> +        System.out.println("bulldozer stop working");
The message in the 'stopWork' method should be in English and start with a capital letter to maintain consistency and professionalism. Additionally, the message should be more informative. For example: 'Bulldozer has stopped its work.'

2024-07-26 17:19 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/Excavator.java
> +        System.out.println("Excavator start working");
The message 'Excavator start working' could be more informative. According to the checklist, it should indicate that it's an Excavator that is working. Consider rephrasing it to something like 'Excavator is starting its work' to make it clear and informative.

2024-07-26 17:19 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/Excavator.java
> +        System.out.println("Excavator stop working");
Similarly, the stop message 'Excavator stop working' should be more informative and indicate clearly that it's an Excavator that has stopped working. A better message would be 'Excavator has stopped working'.

2024-07-26 17:19 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/MainApp.java
> +        Machine [] machines = new Machine[] {bulldozer,excavator,truck};
Please ensure proper spacing after commas in the array initialization to adhere to Java code style guidelines. It should be `new Machine[] {bulldozer, excavator, truck};`

2024-07-26 17:19 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/Truck.java
> +        System.out.println("Truck start working");
The message should be more informative and indicate the specific type of machine that is working. For example: 'Truck started its work.'

2024-07-26 17:19 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/Truck.java
> +        System.out.println("Truck stop working");
Similarly, the stop message should be more descriptive. Consider 'Truck has stopped working.' to provide more clarity.

2024-07-26 18:26 UTC, MentorMateAcademy approved these changes

2024-07-26 18:27 UTC, MentorMateAcademy requested changes
Fix your checks

2024-07-27 06:47 UTC, layzimayner commented
![Снимок экрана 2024-07-27 094606](https://github.com/user-attachments/assets/dd255ab6-3e43-4692-92e1-11ec24af906f)
Culd you explain what's wrong?

2024-07-30 09:27 UTC, closed without merging