1
mate-academy/jv-oop pull request #2208
Opened 2024-11-14 17:44 UTC by YarikNarozhnyi

1

2024-11-14 17:46 UTC, mateacademy-ai-mentor approved these changes
Great job on implementing the `Machine` class hierarchy! 🚜 While your code has a solid foundation, there are a few key areas to address to ensure it functions correctly:

1. **Syntax Errors**: Ensure all `System.out.println` statements in the `Bulldozer`, `Truck`, and `Excavator` classes end with semicolons. This is crucial for the code to compile and run.

2. **Code Structure**: The `for` loop in the `MainApp` class should be placed inside a method, such as the `main` method, to execute properly.

3. **Access Modifiers**: Consider adding an access modifier to the `Machine` array in `MainApp` to adhere to encapsulation principles.

4. **Redundant Empty Lines**: Remove any unnecessary empty lines after class declarations or method signatures for cleaner code.

Your effort is commendable, and addressing these issues will enhance your understanding and coding skills. Keep up the good work, and remember to learn from these points to avoid similar issues in the future. Happy coding! 😊

✨ Please rate this review in the Platform's notification center. I will be grateful for your feedback! ✨

2024-11-14 17:46 UTC, mateacademy-ai-mentor commented on src/main/Bulldozer.java
> +    System.out.println("Bulldozer started working")
There is a missing semicolon at the end of this line. Java statements must end with a semicolon.

2024-11-14 17:46 UTC, mateacademy-ai-mentor commented on src/main/Bulldozer.java
> +    System.out.println("Bulldozer stopped working")
There is a missing semicolon at the end of this line. Java statements must end with a semicolon.

2024-11-14 17:46 UTC, mateacademy-ai-mentor commented on src/main/Excavator.java
> +    System.out.println("Excavator started working")
There is a missing semicolon at the end of this line. Java statements must end with a semicolon.

2024-11-14 17:46 UTC, mateacademy-ai-mentor commented on src/main/Excavator.java
> +    System.out.println("Excavator stopped working")
There is a missing semicolon at the end of this line. Java statements must end with a semicolon.

2024-11-14 17:46 UTC, mateacademy-ai-mentor commented on src/main/Truck.java
> +    System.out.println("Truck started working")
There is a missing semicolon at the end of this line. Java statements must end with a semicolon.

2024-11-14 17:46 UTC, mateacademy-ai-mentor commented on src/main/Truck.java
> +    System.out.println("Truck stopped working")
There is a missing semicolon at the end of this line. Java statements must end with a semicolon.

2024-11-14 17:46 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/MainApp.java
> +    Machine[] machine = new Machine[]{new Truck(), new Bulldozer(), new Excavator()};
The array declaration is correct, but the loop that follows is not properly enclosed within a method. In Java, code must be inside a method or constructor.

2024-11-14 17:46 UTC, mateacademy-ai-mentor commented on src/main/java/core/basesyntax/MainApp.java
> +for (int i = 0;i < machine.length;i++) {
The `for` loop is not inside any method or constructor. You need to place this loop inside a `main` method or another method to execute it properly.

2024-11-14 17:58 UTC, YarikNarozhnyi commented
2

2024-11-14 18:08 UTC, YarikNarozhnyi commented
3

2024-11-14 18:21 UTC, YarikNarozhnyi commented
5

2024-11-15 07:33 UTC, volodymyr-soltys97 requested changes
Hi, this task isn't frontend course, you need to switch to another course on the platform

2024-11-24 12:41 UTC, closed without merging