added homework OOP
mate-academy/jv-oop pull request #445
Opened 2021-10-29 20:13 UTC by Cergei998

2021-11-01 09:31 UTC, RomanDubovskyi requested changes

2021-11-01 09:31 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/MainApp.java
> +        Excavator excavator = new Excavator();
```suggestion
        Machine excavator = new Excavator();
```
хорошою практикою вважається оголошення більш абстракного посилання для змінною (абстрактний клас / інтерфейс). Це потрібно для того, що можна було легко підміняти імплементації

2021-11-01 09:31 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/Machine.java
> +    public abstract void stopWork();
```suggestion
    public abstract void doWork();
    
    public abstract void stopWork();
```
методи потрібно розділяти пустою строкою

2021-11-02 16:51 UTC, closed without merging

2021-11-02 16:55 UTC, Cergei998 commented
Привет, Роман. У меня не получается запушить исправленные файлы. В чате сообщил, но никто не отвечает. 
Может мне как то заново начать делать эту задачу или ждать помощи, совета?