Machine
mate-academy/jv-oop pull request #759
Opened 2022-06-16 06:59 UTC by SerhiiAN

2022-06-16 14:53 UTC, SerhiiAN commented
Доброго вечора, в терміналі коли я прописую данну команду bash: mvn: command not found, я отримую таке повідомлення.

2022-06-17 15:07 UTC, MaliukDaria commented
> mvn: command not found,

2022-06-17 15:07 UTC, closed without merging

2022-06-19 08:27 UTC, SerhiiAN commented
![Снимок1906](https://user-images.githubusercontent.com/107151150/174472433-6ea60458-2429-4e19-b7db-3c25bf00cd27.JPG)
Налаштував maven таке повідомлення я розумію що без помилок.

2022-06-21 13:54 UTC, SerhiiAN commented
Я виправив помилки які Ви вказували, ще щось не так?

2022-06-22 12:00 UTC, Nick97-git requested changes

2022-06-22 12:00 UTC, Nick97-git commented on src/main/java/core/basesyntax/Machine.java
> +    private String nameMachine;
you didn't need to create this field, remove it

2022-06-22 12:00 UTC, Nick97-git commented on src/main/java/core/basesyntax/MainApp.java
> +        String[] machine = new String[] {"Truck", "Bulldozer", "Excavator"};
you should create a Machine array instead

2022-06-22 12:00 UTC, Nick97-git commented on src/main/java/core/basesyntax/Truck.java
> +
the same

2022-06-22 12:00 UTC, Nick97-git commented on src/main/java/core/basesyntax/Truck.java
> +
the same

2022-06-22 12:59 UTC, Nick97-git requested changes

2022-06-22 12:59 UTC, Nick97-git commented on src/main/java/core/basesyntax/Machine.java
> +
remove empty line

2022-06-22 12:59 UTC, Nick97-git commented on src/main/java/core/basesyntax/MainApp.java
> +        for (Machine machineNow : machine) {
```suggestion
        Machine[] machines = new Machine[] {new Truck(), new Bulldozer(), new Excavator()};
        for (Machine machine : machines) {
```

2022-06-22 14:23 UTC, Nick97-git requested changes

2022-06-22 14:23 UTC, Nick97-git commented on src/main/java/core/basesyntax/MainApp.java
> +        Machine[] machine = new Machine[] {new Truck(), new Bulldozer(), new Excavator()};
```suggestion
        Machine[] machines = new Machine[] {new Truck(), new Bulldozer(), new Excavator()};
```

2022-06-23 05:19 UTC, Nick97-git approved these changes